In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
import os
os.chdir("..")

In [3]:
df = pd.read_csv("data/raw/system_data.csv")

In [4]:
df.head()

                    timeStamp  CPU_Usage  Memory_Usage
0  2026-02-05 10:49:30.777540        1.3          84.8
1  2026-02-05 10:49:31.792128        6.0          84.8
2  2026-02-05 10:49:32.800593        4.1          84.8
3  2026-02-05 10:49:33.812465       21.5          84.7
4  2026-02-05 10:49:34.815579       34.6          84.9

In [5]:
df.isnull().sum()

timeStamp       0
CPU_Usage       0
Memory_Usage    0
dtype: int64

In [6]:
df.describe()

         CPU_Usage  Memory_Usage
count  3004.000000   3004.000000
mean     33.758189     88.154028
std      18.991671      3.327697
min       0.400000     78.700000
25%      19.100000     86.000000
50%      30.400000     88.000000
75%      45.100000     90.925000
max     100.000000     97.800000

In [7]:
df["CPU_Usage"] = df["CPU_Usage"].clip(0, 100)
df["Memory_Usage"] = df["Memory_Usage"].clip(0, 100)

In [8]:
df["cpu_scaled"] = df["CPU_Usage"] / 100
df["memory_scaled"] = df["Memory_Usage"] / 100

In [9]:
clean_df = df[["timeStamp", "cpu_scaled", "memory_scaled"]]

In [13]:
import os

print(os.listdir("data/processed"))

[]

In [ ]:
Path("data/processed").mkdir(parents=True, exist_ok=True)
clean_df.to_csv("data/processed/clean_data.csv", index=False)

In [12]:
clean_df.head()

                    timeStamp  cpu_scaled  memory_scaled
0  2026-02-05 10:49:30.777540       0.013          0.848
1  2026-02-05 10:49:31.792128       0.060          0.848
2  2026-02-05 10:49:32.800593       0.041          0.848
3  2026-02-05 10:49:33.812465       0.215          0.847
4  2026-02-05 10:49:34.815579       0.346          0.849