In [11]:
import sqlite3
import pandas as pd
from pathlib import Path

db_path = Path("..") / "performance_logs.db"
conn = sqlite3.connect(db_path)
conn.execute("""
    CREATE TABLE IF NOT EXISTS system_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT,
        cpu REAL,
        memory REAL,
        is_anomaly INTEGER
    )
""")

df = pd.read_sql("SELECT * FROM system_logs ORDER BY id DESC LIMIT 10", conn)
df

     id                   timestamp   cpu  memory  is_anomaly
0  1877  2026-02-06 10:25:50.222777  10.0    80.1           1
1  1876  2026-02-06 10:25:48.177073   6.7    81.0           1
2  1875  2026-02-06 10:25:46.126928   6.9    80.9           1
3  1874  2026-02-06 10:25:44.078834   9.5    80.9           1
4  1873  2026-02-06 10:25:42.028273   7.4    82.3           0
5  1872  2026-02-06 10:25:39.983428  37.0    86.4           0
6  1871  2026-02-06 10:25:37.931204   9.9    86.5           0
7  1870  2026-02-06 10:25:35.876431  14.8    86.3           0
8  1869  2026-02-06 10:25:33.822004  10.1    86.3           0
9  1868  2026-02-06 10:25:31.772434  22.9    86.3           0

In [12]:
import sqlite3
import pandas as pd
from pathlib import Path

db_path = Path("..") / "performance_logs.db"
conn = sqlite3.connect(db_path)
conn.execute("""
    CREATE TABLE IF NOT EXISTS system_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT,
        cpu REAL,
        memory REAL,
        is_anomaly INTEGER
    )
""")

df = pd.read_sql("SELECT * FROM system_logs", conn)

print("Total rows:", len(df))
df.head()

Total rows: 1877

   id                   timestamp   cpu  memory  is_anomaly
0   1  2026-02-05 19:03:17.760209   8.5    90.5           0
1   2  2026-02-05 19:03:19.802301  10.4    90.6           0
2   3  2026-02-05 19:03:21.847580   7.2    90.6           0
3   4  2026-02-05 19:03:23.906597   2.4    90.6           0
4   5  2026-02-05 19:03:25.976304  13.5    91.6           0